name: VTK_Side37
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.7.16
  - pip=22.3.1
  
  # Qt stack (from defaults)
  - pyside2=5.15.2.1=py37haa95532_2  # Verified available
  - shiboken2=5.15.2.1=py37haa95532_2  # Install before other packages
  
  # Matplotlib workaround
  - matplotlib-base=3.4.0=py37h03978a9_0  # Core without GUI dependencies
  
  # VTK stack
  - vtk=9.2.6=py37h6e5a350_0  # Specific build
  - pyvista=0.38.3=pyhd8ed1ab_0
  
  # Remaining dependencies
  - numpy=1.21.6=py37h7a0a035_2
  - scipy=1.7.3=py37h5a1e8f8_1
  - pandas=1.3.5=py37h03978a9_0
  
  # Pip section
  - pip:
    - pyradiomics==3.0.1
    - matplotlib==3.4.0  # Full version via pip
    - opencv-python-headless==4.5.4.60