name: VTK_Side37
channels:
  - conda-forge
  - defaults
dependencies:
  # Base dependencies
  - python=3.7.16
  - pip=22.3.1
  
  # Core scientific stack
  - numpy=1.21.6
  - scipy=1.7.3
  - pandas=1.3.5
  - matplotlib=3.4.0
  
  # VTK/PyVista ecosystem
  - vtk=9.2.6
  - pyvista=0.38.3
  - pyvistaqt=0.9.1
  
  # Medical imaging
  - pyradiomics=3.0.1
  - simpleitk=2.0.2
  
  # Qt GUI
  - pyside2=5.15.2.1
  - qtpy=2.3.0
  
  # Image processing
  - opencv=4.5.4
  - scikit-image=0.19.3
  - pillow=9.4.0
  
  # Utilities
  - psutil=5.9.4
  - networkx=2.6.3
  - joblib=1.2.0
  
  # Dependency management
  - setuptools=65.6.3
  - wheel=0.38.4
  
  # Pip-only dependencies
  - pip:
    - meshio==5.3.4
    - pykwalify==1.8.0
    - markdown-it-py==2.2.0
    - rich==13.3.1
    - opencv-python-headless==4.5.4.60  # Lighter than full opencv
    - et-xmlfile==1.1.0
    - openpyxl==3.1.1